<?php
/**
 * ACF Field Group — Registrar todos os campos via código.
 *
 * @package UQBITZ_Hub_Imoveis
 */

defined( 'ABSPATH' ) || exit;

add_action( 'acf/init', 'uqbhi_register_acf_fields' );

/**
 * Register all ACF field groups for uqbhi_imovel.
 */
function uqbhi_register_acf_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_uqbhi_dados_imovel',
			'title'                 => 'Dados do Imóvel',
			'fields'                => array(
				array(
					'key'               => 'field_69346d00741b8',
					'label'             => 'Referência',
					'name'              => 'referencia',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 0,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a34f9ef21',
					'label'             => 'Preço Venda',
					'name'              => 'sell_price',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'Apenas números, sem pontuação.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 0,
					'placeholder'       => 1000000,
					'step'              => '',
					'prepend'           => 'R$',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a49b9ef2a',
					'label'             => 'Preço Locação',
					'name'              => 'rent_price',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'Apenas números, sem pontuação.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 0,
					'placeholder'       => 1000,
					'step'              => '',
					'prepend'           => 'R$',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a5109ef2c',
					'label'             => 'IPTU',
					'name'              => 'iptu',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'Apenas números, sem pontuação.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => 'R$',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a4889ef29',
					'label'             => 'Condomínio',
					'name'              => 'condominium',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'Apenas números, sem pontuação.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => 'R$',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a3c29ef22',
					'label'             => 'Área privativa',
					'name'              => 'metreage',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '16',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => 1,
					'prepend'           => '',
					'append'            => 'm²',
				),
				array(
					'key'               => 'field_6206a4379ef25',
					'label'             => 'Vagas',
					'name'              => 'parking',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a40b9ef23',
					'label'             => 'Quartos',
					'name'              => 'rooms',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a4709ef28',
					'label'             => 'Banheiros',
					'name'              => 'bathroom',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_6206a42b9ef24',
					'label'             => 'Suítes',
					'name'              => 'suits',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_69344a6423ef3',
					'label'             => 'Torres',
					'name'              => 'torres',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_69344a7323ef4',
					'label'             => 'Andares',
					'name'              => 'andares',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_69344a7d23ef5',
					'label'             => 'Idade',
					'name'              => 'idade',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'allow_in_bindings' => 1,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'                       => 'field_6206a4409ef26',
					'label'                     => 'Amenidades',
					'name'                      => 'amenities',
					'aria-label'                => '',
					'type'                      => 'checkbox',
					'instructions'              => '',
					'required'                  => 0,
					'conditional_logic'         => 0,
					'wrapper'                   => array(
						'width' => '100',
						'class' => '',
						'id'    => '',
					),
					'choices'                   => array(
						'Aquecedor'                 => 'Aquecedor',
						'Ar condicionado'           => 'Ar condicionado',
						'Biblioteca'                => 'Biblioteca',
						'Churrasqueira'             => 'Churrasqueira',
						'Closet'                    => 'Closet',
						'Cozinha americana'         => 'Cozinha americana',
						'Cozinha gourmet'           => 'Cozinha gourmet',
						'Cozinha independente'      => 'Cozinha independente',
						'Cozinha planejada'         => 'Cozinha planejada',
						'Dependência de empregados' => 'Dependência de empregados',
						'Despensa'                  => 'Despensa',
						'Entrada independente'      => 'Entrada independente',
						'Escritório'                => 'Escritório',
						'Espaço gourmet'            => 'Espaço gourmet',
						'Jardim'                    => 'Jardim',
						'Lareira'                   => 'Lareira',
						'Lava-louça'                => 'Lava-louça',
						'Lavabo'                    => 'Lavabo',
						'Lavanderia'                => 'Lavanderia',
						'Mezanino'                  => 'Mezanino',
						'Mobiliado'                 => 'Mobiliado',
						'Permite animais'           => 'Permite animais',
						'Piscina (privativa)'       => 'Piscina (privativa)',
						'Playground (privativo)'    => 'Playground (privativo)',
						'Quintal'                   => 'Quintal',
						'Sala de estar'             => 'Sala de estar',
						'Sala de jantar'            => 'Sala de jantar',
						'Varanda'                   => 'Varanda',
						'Varanda gourmet'           => 'Varanda gourmet',
						'Área de serviço'           => 'Área de serviço',
					),
					'default_value'             => array(),
					'return_format'             => 'value',
					'allow_custom'              => 1,
					'save_custom'               => 1,
					'allow_in_bindings'         => 0,
					'layout'                    => 'horizontal',
					'toggle'                    => 0,
					'custom_choice_button_text' => 'Adicionar nova escolha',
				),
				array(
					'key'               => 'field_6934236aada5c',
					'label'             => 'Descrição',
					'name'              => 'descricao',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'allow_in_bindings' => 0,
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_uqbhi_cep',
					'label'             => 'CEP',
					'name'              => 'cep',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => 9,
					'placeholder'       => '00000-000',
					'prepend'           => '',
					'append'            => '',
				),

				array(
					'key'               => 'field_uqbhi_bairro',
					'label'             => 'Bairro',
					'name'              => 'bairro',
					'type'              => 'text',
					'instructions'      => 'Auto-preenchido pelo CEP.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '30',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'readonly'          => 1,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),

				array(
					'key'               => 'field_uqbhi_cidade',
					'label'             => 'Cidade',
					'name'              => 'cidade',
					'type'              => 'text',
					'instructions'      => 'Auto-preenchido pelo CEP.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '30',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'readonly'          => 1,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),

				array(
					'key'               => 'field_uqbhi_estado',
					'label'             => 'Estado',
					'name'              => 'estado',
					'type'              => 'text',
					'instructions'      => 'Auto-preenchido pelo CEP.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'readonly'          => 1,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),

				array(
					'key'               => 'field_6206a5c2635cb',
					'label'             => 'Rua',
					'name'              => 'location',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Auto-preenchido pelo CEP.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '70',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'placeholder'       => 'Preenchido pelo CEP',
					'prepend'           => '',
					'append'            => '',
					'readonly'          => 0,
				),

				array(
					'key'               => 'field_uqbhi_numero',
					'label'             => 'Número',
					'name'              => 'numero',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Opcional, mas recomendado para melhor posicionamento nas buscas.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '15',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '10',
					'allow_in_bindings' => 0,
					'placeholder'       => 'Nº',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_uqbhi_complemento',
					'label'             => 'Complemento',
					'name'              => 'complemento',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Apto, Bloco, Sala, etc.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '15',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'placeholder'       => 'Apto 101',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'                       => 'field_693423b6a9e79',
					'label'                     => 'Infraestrutura',
					'name'                      => 'infraestrutura',
					'aria-label'                => '',
					'type'                      => 'checkbox',
					'instructions'              => '',
					'required'                  => 0,
					'conditional_logic'         => 0,
					'wrapper'                   => array(
						'width' => '100',
						'class' => '',
						'id'    => '',
					),
					'choices'                   => array(
						'Academia'                       => 'Academia',
						'Acesso PNE'                     => 'Acesso PNE',
						'Aquecimento central'            => 'Aquecimento central',
						'Banheiro na área comum'         => 'Banheiro na área comum',
						'Bicicletário'                   => 'Bicicletário',
						'Biometria'                      => 'Biometria',
						'Biribol'                        => 'Biribol',
						'Brinquedoteca'                  => 'Brinquedoteca',
						'Campo de futebol'               => 'Campo de futebol',
						'Churrasqueira (comum)'          => 'Churrasqueira (comum)',
						'Cinema'                         => 'Cinema',
						'Condomínio fechado'             => 'Condomínio fechado',
						'Câmeras de segurança'           => 'Câmeras de segurança',
						'Depósito privativo'             => 'Depósito privativo',
						'Ducha'                          => 'Ducha',
						'Elevador'                       => 'Elevador',
						'Elevador de serviço'            => 'Elevador de serviço',
						'Entrada de serviço'             => 'Entrada de serviço',
						'Espaço car'                     => 'Espaço car',
						'Espaço gourmet (comum)'         => 'Espaço gourmet (comum)',
						'Espaço mulher'                  => 'Espaço mulher',
						'Estacionamento coberto'         => 'Estacionamento coberto',
						'Estacionamento para visitantes' => 'Estacionamento para visitantes',
						'Facial'                         => 'Facial',
						'Guarita'                        => 'Guarita',
						'Hidromassagem'                  => 'Hidromassagem',
						'Horta'                          => 'Horta',
						'Interfone'                      => 'Interfone',
						'Jardim'                         => 'Jardim',
						'Lava rápido'                    => 'Lava rápido',
						'Mercadinho 24h'                 => 'Mercadinho 24h',
						'Parede de escalada'             => 'Parede de escalada',
						'Piscina'                        => 'Piscina',
						'Piscina (comum)'                => 'Piscina (comum)',
						'Piscina infantil'               => 'Piscina infantil',
						'Pista de skate'                 => 'Pista de skate',
						'Pista para caminhada'           => 'Pista para caminhada',
						'Playground'                     => 'Playground',
						'Portaria'                       => 'Portaria',
						'Portaria 24h'                   => 'Portaria 24h',
						'Quadra de basquete'             => 'Quadra de basquete',
						'Quadra de tênis'                => 'Quadra de tênis',
						'Quadra poliesportiva'           => 'Quadra poliesportiva',
						'SPA'                            => 'SPA',
						'Salão de festas'                => 'Salão de festas',
						'Salão de jogos'                 => 'Salão de jogos',
						'Sauna'                          => 'Sauna',
						'Solarium'                       => 'Solarium',
						'Vagas PNE'                      => 'Vagas PNE',
						'Vestiário'                      => 'Vestiário',
						'Vigilância 24h'                 => 'Vigilância 24h',
						'Zelador'                        => 'Zelador',
						'Área de lazer'                  => 'Área de lazer',
						'Área pet'                       => 'Área pet',
						'Área verde'                     => 'Área verde',
					),
					'default_value'             => array(),
					'return_format'             => 'value',
					'allow_custom'              => 1,
					'save_custom'               => 1,
					'allow_in_bindings'         => 0,
					'layout'                    => 'horizontal',
					'toggle'                    => 0,
					'custom_choice_button_text' => 'Adicionar nova escolha',
				),
				array(
					'key'               => 'field_69341be209f2d',
					'label'             => 'Galeria de Imagens',
					'name'              => 'galeria_de_imagens',
					'aria-label'        => '',
					'type'              => 'gallery',
					'instructions'      => 'Recomendamos pelo menos 22 fotos de ângulos e ambientes diferentes. Imóveis com mais fotos têm até 17% mais chance de aparecer melhor posicionados nos resultados de busca.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min'               => '',
					'max'               => '',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'insert'            => 'append',
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_6960faeaba8d9',
					'label'             => 'Vídeo do YouTube',
					'name'              => 'video_youtube',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Cole o link do YouTube do vídeo do imóvel. O código será extraído automaticamente. Ex: https://www.youtube.com/watch?v=rs12I4SfBkCY',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placeholder'       => 'https://www.youtube.com/watch?v=...',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key'               => 'field_uqbhi_plantas',
					'label'             => 'Plantas do Imóvel',
					'name'              => 'plantas',
					'aria-label'        => '',
					'type'              => 'gallery',
					'instructions'      => 'Envie as plantas (plantas baixas) do imóvel. Cada imagem será exportada com seu título no XML do feed.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min'               => '',
					'max'               => '',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => 'jpg,jpeg,png,webp',
					'insert'            => 'append',
					'preview_size'      => 'medium',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'uqbhi_imovel',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
		)
	);

	// When ACF Pro is absent, strip the gallery fields — a native metabox
	// fallback renders the UI (see includes/gallery-fallback.php).
	if ( ! uqbhi_has_acf_pro_gallery() ) {
		acf_remove_local_field( 'field_69341be209f2d' ); // galeria_de_imagens.
		acf_remove_local_field( 'field_uqbhi_plantas' ); // plantas.
	}
}
